- name: Check if resolv.conf file exists
  stat:
      path: /etc/resolv.conf
  register: file_info

- name: Create /etc/resolv.conf if it exists
  file:
    path: /etc/resolv.conf
    state: touch
  when: not file_info.stat.exists

- name: Set 403 DNS nameservers in /etc/resolv.conf
  blockinfile:
      path: /etc/resolv.conf
      block: |
            nameserver 10.202.10.202
            nameserver 10.202.10.102
            nameserver 4.2.2.4
