- name: Check if resolv.conf file exists
  stat:
      path: /etc/resolv.conf
  register: file_info

- name: Create /etc/resolv.conf if it exists
  file:
    path: /etc/resolv.conf
    state: touch
  when: not file_info.stat.exists

- name: Set Shecan DNS nameservers in /etc/resolv.conf
  blockinfile:
      path: /etc/resolv.conf
      block: |
            nameserver 178.22.122.100
            nameserver 185.51.200.2
            nameserver 4.2.2.4
