---

- hosts: dev
  become: yes
  tasks:
    # - name: packages | ensure apt list dir exists
    #   file:
    #     path: /var/lib/apt/lists/
    #     state: directory
    #     mode: 0755
  - name: this will install docker on remote
    apt: 
      name : vim
      state: latest

...